spring:
  application:
    name: Findex
  config:
    import: application-secret.yml
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql


external:
  api:
    baseurl: https://apis.data.go.kr/1160100/service/GetMarketIndexInfoService





