spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate # 운영 배포 시엔 none 또는 validate 권장
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: Findex
  config:
    import: application-secret.yml
  task:
    scheduling:
      enabled: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect


batch:
  sync:
    info:
      fixed-delay: PT40S
    enabled-index-data:
      fixed-delay: P1D

logging:
  level:
    org.springframework.data.jpa.domain.support.AuditingEntityListener : DEBUG
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

external:
  api:
    baseurl: https://apis.data.go.kr/1160100/service/GetMarketIndexInfoService

server:
  forward-headers-strategy: framework
