spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/team3 # DB이름 설정 필요
    username: team3
    password: team3123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create # 개발 단계는 update, 운영은 none 권장
    show-sql: true       # 실행 쿼리 확인
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅 가독성
  application:
    name: Findex
  config:
    import: application-secret.yml
  task:
    scheduling:
      enabled: true

batch:
  sync:
    info:
      fixed-delay: PT40S               # syncInfoAndSave: 종료 후 40초 대기
    enabled-index-data:
      fixed-delay: P1D

# Logging 설정
logging:
  level:
    org.springframework.data.jpa.domain.support.AuditingEntityListener : DEBUG
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace



#  sql:
#    init:
#      mode: update
#      schema-locations: classpath:schema.sql

external:
  api:
    baseurl: https://apis.data.go.kr/1160100/service/GetMarketIndexInfoService

server:
  forward-headers-strategy: framework
